import sqlite3
db=sqlite3.connect('storemanagement.db')
conn=db.cursor()
#create=conn.execute('drop table register')
#create=conn.execute('drop table cart')
#create=conn.execute('drop table object')
#create=conn.execute('create table register(emailId varchar(20) not null primary key ,password varchar(20),addr varchar(50),city varchar(20),pin varchar (10),job varchar (20))')
create=conn.execute('create table cart(objId int not null ,eid varchar ,objName varchar ,objVal int (10),price int,val int,Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,foreign key (eid) references register(emailId))')
#create=conn.execute('create table object(obid int not null primary key ,objname varchar ,image message_text ,prevPrice int (10),curPrice int (10),addingTime DATETIME DEFAULT CURRENT_TIMESTAMP)')
#cur.execute("INSERT INTO register (emailId,objName,objVal) VALUES(?, ?, ?)", (emailId, objName, objVal))
#insert=conn.execute("INSERT INTO register (name,password,addr,city,pin) VALUES(?, ?, ?, ?, ?)",(nm,ps,addr,city,pin) )
#create=conn.execute('alter table register add column job varchar (20)')
#create=conn.execute("describe register")
#aa=create.fetchall()
#print(aa)
db.commit()